server:
  port: 8088
  
spring:
  application:
    name: 'auth'
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka      